name: Node CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: build_push_tag of main
     
      
      env:      
       PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
       USERNAME: ${{ secrets.DOCKER_USERNAME }}  
      
     
      run: |
            
             sudo docker login -u $USERNAME -p $PASSWORD
             sudo docker build -t nodetestex:latest .
             sudo docker run -it -d -p 8080:8080 nodetestex

